### ISSUE TITLE
Is there a way to modify this to hook into an exported windows godot project ?

### ISSUE THREAD

**Issue by drewdus42** [BoyneGames/streamdeck-godot-plugin#1]
If this hooks into the running instance of godot you have... is there a way to modify this to interact the same way of like triggering signals, but hooked into the actual project or program you export?

I'm making a video player in godot and would love to make a streamdeck plugin for it. I'm wondering if this can be used as a base...

**Comment by BoyneGames** [comment]
Yes, when you export your Godot project as an executable it will build with the plugin to connect to the Elgato Stream Deck software. This is the default behavior of this plugin, so your Godot application can listen to button presses - not the Godot editor itself.

**Comment by drewdus42** [comment]
That's slick! thanks
