### ISSUE TITLE
change default port please

### ISSUE THREAD

**Issue by DelToney** [BoyneGames/streamdeck-godot-plugin#2]
I know its a nitpick but i just ran into an issue where i was so confused trying to dev my webpack server on 8080 and trying to go on a huge goose chase for what program was holding 8080, and found it was this plugin. defaulting to 9090 would be nice for us web devs since its outta the way. Thankuuuu!~

**Comment by BoyneGames** [comment]
Hey, thanks for the feedback. I can definitely look into changing the default port to something else that doesn't interfere with local servers like Webpack.

As a workaround, it's actually possible to change the default port of the plugin. 

To do this, first locate the Elgato Stream Deck software's plugins directory:

MacOS:
`~/Library/Application Support/com.elgato.StreamDeck/Plugins/`

Windows:
`%appdata%\Elgato\StreamDeck\Plugins\` 

Then locate the directory for this plugin (`games.boyne.godot.sdPlugin`) and open up `plugin.ini`, and amend the `port` attribute to something else:

![Screenshot 2023-10-24 at 17 53 55](https://github.com/BoyneGames/streamdeck-godot-plugin/assets/128102473/31edc818-6f53-41bf-bdb3-115bd0d88ada)

Make sure to close and re-open the Elgato Stream Deck software.

~~After this, you'll also need to amend [this line](https://github.com/BoyneGames/streamdeck-godot-plugin/blob/main/godot-streamdeck-addon/singleton.gd#L64) in the Godot plugin itself and replace `8080` with your new port.~~

**Comment by DelToney** [comment]
definitely fixed it for me, though i didnt need to edit the port number in the gd script. if it does end up being a bug or something, it would be nice to not have to edit the gd script and just have everything based off the ini file :)

**Comment by BoyneGames** [comment]
Ah, that's right. The Godot plugin itself also parses the `plugin.ini` file, but defaults to `8080` in the absence of it.
